dist: trusty
sudo: false
language: node_js
node_js:
- 8
notifications:
  email:
    on_failure: change
    on_success: change
branches:
  only:
  - master
  - stage
  - prod
cache:
  directories:
  - "$HOME/.npm"
install:
- npm i
- npm i firebase-ci@^0.5.0
script:
  - npm run lint
  - npm run build
addons:
  code_climate:
    repo_token: "$CODE_CLIMATE"
deploy:
- provider: s3
  skip_cleanup: true
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: workpals-bucket
  local-dir: build
  acl: bucket_owner_full_control
  region: us-east-2
  on:
    repo: WorkPalsCO/Frontend
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: workpals-bucket
  key: latest.zip
  bundle_type: zip
  application: WorkPalsCD
  deployment_group: WorkPalsCD
  region: us-east-2
  on:
    repo: WorkPalsCO/Frontend
script:
- zip -r latest build --quiet
- mkdir -p build
- mv latest.zip build/latest.zip